feat(zsh): make `portool run bundle` work on older branches
Just noticed this testing a bundle on an older DXP branch (7.1.x), that
it is using an older version of tomcat (9.0.33 vs 9.0.37), so the
hard-coded `$TOMCAT` won't work. Let's autodetect it instead.

The other thing it's going to choke on is the MySQL driver name in the
portal-ext.properties; that one is going to be harder to autodetect,
so I'm just leaving this here as a reminder for posterity: on old
branches you are going to want `com.mysql.cj.jdbc.Driver` instead of
`com.mysql.jdbc.Driver`,and will have to edit it by hand.

diff --git a/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/run b/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/run
--- a/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/run
+++ b/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/run
@@ -18,6 +18,11 @@ case "$1" in
 
     echo "🔎 Launching tomcat with bundle settings"
     PORTAL_BUNDLES=$PWD
+    TOMCAT=$(find tomcat-* -name catalina.sh | head -1 | sed -e "s#/.*##")
+    if [ -z "$TOMCAT" ]; then
+      echo "error: failed to find catalina.sh"
+      exit 1
+    fi
     SOURCE=~/code/portal/bundles/portal-ext.properties.bundle
     ln -sf "$SOURCE" portal-ext.properties
           ;;
