feat(zsh): make `portool yarn` use local yarn too
It used to just use the local node, but we can make it try to use the
local yarn too.

For example, on my system right now, I have Yarn 1.22.5, but DXP is
still on 1.13.0.

diff --git a/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/yarn b/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/yarn
--- a/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/yarn
+++ b/aspects/dotfiles/files/.zsh/liferay/bin/portool-helpers/yarn
@@ -5,5 +5,19 @@
 source "${BASH_SOURCE%/*}/.common.sh"
 
 NODE_BINDIR=$(node_path)
+YARN_DIR=$(realpath "$NODE_BINDIR/../lib/node_modules/yarn")
 
-env PATH="$NODE_BINDIR:$PATH" yarn "$@"
+if [ -d "$YARN_DIR" ]; then
+  YARN_EXE=$(find "$YARN_DIR" -name 'yarn-*.js' | head -1)
+  if [ -f "$YARN_EXE" ]; then
+    echo "info: using $YARN_EXE" >&2
+  else
+    YARN_EXE=$(command -v yarn)
+    echo "warning: could not find yarn executable; falling back to global $YARN_EXE" >&2
+  fi
+else
+  YARN_EXE=$(command -v yarn)
+  echo "warning: could not find yarn executable; falling back to global $YARN_EXE" >&2
+fi
+
+env PATH="$NODE_BINDIR:$PATH" node "$YARN_EXE" "$@"
